server:
  host: "localhost"
  port: 8080
db:
  dbname: "wb"
  host: "localhost"
  user: "wb_user"
  password: "1234"
  port: 5432
  sslmode: disable
nats:
  cluster: "test-cluster"
  url: "nats://localhost:4222"
  client: "order-service-client"
  clientnotifier: "notifier-client"
  subject: "order"
  durablename: "order-durable-subscription"